# Dataset / Model parameters
data_dir: ./deap/
dataset: DEAP
pretrained: False
num_classes: 2
num_heads: 8
in_channels: 1
pps_size_h: 8
img_size_h: 32
img_size_w: 512
log_interval: 100
use_conv_as_linear: true
pooling_stat: "0011"
time_steps: 4
layer: 1
dim: 128
mlp_ratio: 1
patch_size: 2
# Model Exponential Moving Average
model-ema: False
model-ema-decay: 0.9998

# Misc
seed: 42
amp: True
channels-last: False
batch_size: 32
val_batch_size: 32
lr: 1e-3
min_lr: 1e-5
sched: cosine
weight_decay: 1e-3
epochs: 40
cooldown_epochs: 10
warmup_epochs: 10
warmup_lr: 1e-4
opt: adamw
bce_loss: 1
smoothing: 0.1
bce_target_thresh: 0.05
workers: 1
drop_path: 0.3

val_mode: "LOSO"
time_window: 4 #second
label_index: 0 #0-3 0-Valence 1-Arousal 2-Dominance 3-Liking
#current_idx: 16 #1-32
#LOSO
file_range: 32
#LOTO
current_trail_idx: 0 #0-39


